-- MySQL Script generated by MySQL Workbench
-- 04/27/15 16:02:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jobplix
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jobplix` ;

-- -----------------------------------------------------
-- Schema jobplix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobplix` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `jobplix` ;

-- -----------------------------------------------------
-- Table `jobplix`.`ubigeo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`ubigeo` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`ubigeo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod_pais` VARCHAR(45) NOT NULL,
  `cod_region` VARCHAR(45) NOT NULL,
  `cod_postal` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`sexo` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`sexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`disponibilidad_horaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`disponibilidad_horaria` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`disponibilidad_horaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`grado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`grado` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`grado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  `gradocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`enfermedades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`enfermedades` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`enfermedades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`situacion_financiera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`situacion_financiera` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`situacion_financiera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`nivel_educativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`nivel_educativo` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`nivel_educativo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`especializacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`especializacion` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`especializacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_emision` VARCHAR(45) NULL,
  `fecha_caduca` VARCHAR(45) NULL,
  `emisor` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`candidato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`candidato` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`candidato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `medida_talla` VARCHAR(45) NULL,
  `medida_peso` VARCHAR(45) NULL,
  `num_dependientes` VARCHAR(45) NULL,
  `color_ojos` VARCHAR(45) NULL,
  `disponibilidad_inmediata` TINYINT(1) NULL DEFAULT 1 COMMENT 'campo disponibilidad_inmediata por defecto 1 = SI (opciones: 0 -> NO, 1 -> SI)',
  `anteced_judiciales` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'campo anteced_judiciales por defecto 0 = NO (opciones: 0 NO, 1 SI)',
  `anteced_policiales` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'campo anteced_policiales por defecto 0 = NO (opciones: 0 NO, 1 SI)',
  `discapacidad` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'campo discapacidad por defecto 0 = NO (opciones: 0 NO, 1 SI)',
  `movilidad_propia` TINYINT(1) NULL DEFAULT 0 COMMENT 'campo movilidad_propia por defecto 0 = NO (opciones: 0 NO, 1 SI)',
  `estado_civil_id` INT NOT NULL,
  `ubigeo_nacimiento_id` INT NOT NULL,
  `ubigeo_residencia_id` INT NOT NULL,
  `sexo_id` INT NOT NULL,
  `disponibilidad_horaria_id` INT NOT NULL,
  `grado_alcanzado_id` INT NOT NULL,
  `enfermedades_id` INT NOT NULL,
  `situacion_financiera_id` INT NOT NULL,
  `nivel_educativo_id` INT NOT NULL,
  `especializacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidato_ubigeo1_idx` (`ubigeo_nacimiento_id` ASC),
  INDEX `fk_candidato_ubigeo2_idx` (`ubigeo_residencia_id` ASC),
  INDEX `fk_candidato_sexo1_idx` (`sexo_id` ASC),
  INDEX `fk_candidato_disponibilidad_horaria1_idx` (`disponibilidad_horaria_id` ASC),
  INDEX `fk_candidato_grado1_idx` (`grado_alcanzado_id` ASC),
  INDEX `fk_candidato_enfermedades1_idx` (`enfermedades_id` ASC),
  INDEX `fk_candidato_situacion_financiera1_idx` (`situacion_financiera_id` ASC),
  INDEX `fk_candidato_nivel_educativo1_idx` (`nivel_educativo_id` ASC),
  INDEX `fk_candidato_especializacion1_idx` (`especializacion_id` ASC),
  CONSTRAINT `fk_candidato_ubigeo1`
    FOREIGN KEY (`ubigeo_nacimiento_id`)
    REFERENCES `jobplix`.`ubigeo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_ubigeo2`
    FOREIGN KEY (`ubigeo_residencia_id`)
    REFERENCES `jobplix`.`ubigeo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_sexo1`
    FOREIGN KEY (`sexo_id`)
    REFERENCES `jobplix`.`sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_disponibilidad_horaria1`
    FOREIGN KEY (`disponibilidad_horaria_id`)
    REFERENCES `jobplix`.`disponibilidad_horaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_grado1`
    FOREIGN KEY (`grado_alcanzado_id`)
    REFERENCES `jobplix`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_enfermedades1`
    FOREIGN KEY (`enfermedades_id`)
    REFERENCES `jobplix`.`enfermedades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_situacion_financiera1`
    FOREIGN KEY (`situacion_financiera_id`)
    REFERENCES `jobplix`.`situacion_financiera` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_nivel_educativo1`
    FOREIGN KEY (`nivel_educativo_id`)
    REFERENCES `jobplix`.`nivel_educativo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_especializacion1`
    FOREIGN KEY (`especializacion_id`)
    REFERENCES `jobplix`.`especializacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`institucion_educativa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`institucion_educativa` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`institucion_educativa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `nombre_institucion` VARCHAR(45) NULL,
  `direccion_institucion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`educacion_superior`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`educacion_superior` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`educacion_superior` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT 'instituto/universidad',
  `institucion_educativa_id` INT NOT NULL,
  `facultad` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_educacion_superior_institucion_educativa1_idx` (`institucion_educativa_id` ASC),
  CONSTRAINT `fk_educacion_superior_institucion_educativa1`
    FOREIGN KEY (`institucion_educativa_id`)
    REFERENCES `jobplix`.`institucion_educativa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`candidato_has_educacion_superior`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`candidato_has_educacion_superior` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`candidato_has_educacion_superior` (
  `candidato_id` INT NOT NULL,
  `educacion_superior_id` INT NOT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `nombre_carrera` VARCHAR(45) NULL,
  PRIMARY KEY (`candidato_id`, `educacion_superior_id`),
  INDEX `fk_candidato_has_educacion_superior_educacion_superior1_idx` (`educacion_superior_id` ASC),
  INDEX `fk_candidato_has_educacion_superior_candidato1_idx` (`candidato_id` ASC),
  CONSTRAINT `fk_candidato_has_educacion_superior_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `jobplix`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_has_educacion_superior_educacion_superior1`
    FOREIGN KEY (`educacion_superior_id`)
    REFERENCES `jobplix`.`educacion_superior` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`idioma` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`idioma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`candidato_has_idiomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`candidato_has_idiomas` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`candidato_has_idiomas` (
  `candidato_id` INT NOT NULL,
  `idiomas_id` INT NOT NULL,
  `nivel` VARCHAR(45) NULL,
  `nativo` TINYINT(1) NULL,
  PRIMARY KEY (`candidato_id`, `idiomas_id`),
  INDEX `fk_candidato_has_idiomas_idiomas1_idx` (`idiomas_id` ASC),
  INDEX `fk_candidato_has_idiomas_candidato1_idx` (`candidato_id` ASC),
  CONSTRAINT `fk_candidato_has_idiomas_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `jobplix`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_has_idiomas_idiomas1`
    FOREIGN KEY (`idiomas_id`)
    REFERENCES `jobplix`.`idioma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`sector_economico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`sector_economico` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`sector_economico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sector_economico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`tipo_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`tipo_empresa` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`tipo_empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`empresa` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RUC` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `tipo_empresa_id` INT NOT NULL,
  `sector_economico_id` INT NOT NULL,
  `url` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `logo` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_sector_economico1_idx` (`sector_economico_id` ASC),
  INDEX `fk_empresa_tipo_empresa1_idx` (`tipo_empresa_id` ASC),
  CONSTRAINT `fk_empresa_sector_economico1`
    FOREIGN KEY (`sector_economico_id`)
    REFERENCES `jobplix`.`sector_economico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_tipo_empresa1`
    FOREIGN KEY (`tipo_empresa_id`)
    REFERENCES `jobplix`.`tipo_empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`categoria_habilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`categoria_habilidad` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`categoria_habilidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`habilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`habilidad` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`habilidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_habilidad_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_habilidad_categoria_habilidad1_idx` (`categoria_habilidad_id` ASC),
  CONSTRAINT `fk_habilidad_categoria_habilidad1`
    FOREIGN KEY (`categoria_habilidad_id`)
    REFERENCES `jobplix`.`categoria_habilidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`tipo_contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`tipo_contrato` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`tipo_contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`experiencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`experiencia` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`experiencia` (
  `candidato_id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `salario_mensual` FLOAT NULL,
  `motivo_cese` VARCHAR(150) NULL,
  `is-current` TINYINT(1) NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `tipo_contrato_id` INT NOT NULL,
  PRIMARY KEY (`candidato_id`, `empresa_id`),
  INDEX `fk_candidato_has_empresa_empresa1_idx` (`empresa_id` ASC),
  INDEX `fk_candidato_has_empresa_candidato1_idx` (`candidato_id` ASC),
  INDEX `fk_candidato_has_empresa_tipo_contrato1_idx` (`tipo_contrato_id` ASC),
  CONSTRAINT `fk_candidato_has_empresa_candidato10`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `jobplix`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_has_empresa_empresa10`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `jobplix`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_has_empresa_tipo_contrato10`
    FOREIGN KEY (`tipo_contrato_id`)
    REFERENCES `jobplix`.`tipo_contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`experiencia_has_habilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`experiencia_has_habilidad` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`experiencia_has_habilidad` (
  `habilidad_id` INT NOT NULL,
  `candidato_id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `nivel` VARCHAR(45) NULL,
  `is-validated` TINYINT(1) NULL,
  `experiencia_candidato_id` INT NOT NULL,
  `experiencia_empresa_id` INT NOT NULL,
  PRIMARY KEY (`habilidad_id`, `candidato_id`),
  INDEX `fk_candidato_has_empresa_has_habilidad_habilidad1_idx` (`habilidad_id` ASC),
  INDEX `fk_candidato_has_empresa_has_habilidad_candidato1_idx` (`candidato_id` ASC),
  INDEX `fk_candidato_has_empresa_has_habilidad_experiencia1_idx` (`experiencia_candidato_id` ASC, `experiencia_empresa_id` ASC),
  CONSTRAINT `fk_candidato_has_empresa_has_habilidad_habilidad1`
    FOREIGN KEY (`habilidad_id`)
    REFERENCES `jobplix`.`habilidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_has_empresa_has_habilidad_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `jobplix`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_has_empresa_has_habilidad_experiencia1`
    FOREIGN KEY (`experiencia_candidato_id` , `experiencia_empresa_id`)
    REFERENCES `jobplix`.`experiencia` (`candidato_id` , `empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`puesto_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`puesto_laboral` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`puesto_laboral` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_puesto_laboral_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_puesto_laboral_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `jobplix`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`opciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`opciones` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`opciones` (
  `id` INT NOT NULL,
  `dato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`variable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`variable` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`variable` (
  `id` INT NOT NULL,
  `nombre_variable` VARCHAR(45) NULL,
  `tabla_dato` VARCHAR(45) NULL,
  `campo_dato` VARCHAR(45) NULL,
  `tabla_opciones` VARCHAR(45) NULL,
  `funcion_preoperacion` VARCHAR(45) NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`variable_de_puesto_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`variable_de_puesto_laboral` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`variable_de_puesto_laboral` (
  `puesto_laboral_id` INT NOT NULL,
  `variable_id` INT NOT NULL,
  `valor_maximo` VARCHAR(45) NULL,
  `tipo_variable` VARCHAR(45) NULL,
  PRIMARY KEY (`puesto_laboral_id`, `variable_id`),
  INDEX `fk_puesto_laboral_has_variable_variable1_idx` (`variable_id` ASC),
  INDEX `fk_puesto_laboral_has_variable_puesto_laboral1_idx` (`puesto_laboral_id` ASC),
  CONSTRAINT `fk_puesto_laboral_has_variable_puesto_laboral1`
    FOREIGN KEY (`puesto_laboral_id`)
    REFERENCES `jobplix`.`puesto_laboral` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_puesto_laboral_has_variable_variable1`
    FOREIGN KEY (`variable_id`)
    REFERENCES `jobplix`.`variable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`patron_de_evaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`patron_de_evaluacion` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`patron_de_evaluacion` (
  `puesto_laboral_id` INT NOT NULL,
  `variable_id` INT NOT NULL,
  `opcion_id` INT NOT NULL,
  `kvi` VARCHAR(45) NULL DEFAULT '1',
  `pvi` VARCHAR(45) NULL DEFAULT '0' COMMENT 'esta tabla tendrá los valores kvi y pvi de  todas las convinaciones delas opciones de las  variables que pueden existir, usar bien la configuración por defecto',
  `variable_de_puesto_laboral_puesto_laboral_id` INT NOT NULL,
  `variable_de_puesto_laboral_variable_id` INT NOT NULL,
  PRIMARY KEY (`puesto_laboral_id`, `variable_id`),
  INDEX `fk_puesto_laboral_has_variable1_variable1_idx` (`variable_id` ASC),
  INDEX `fk_puesto_laboral_has_variable1_puesto_laboral1_idx` (`puesto_laboral_id` ASC),
  INDEX `fk_puesto_laboral_has_variable1_opciones1_idx` (`opcion_id` ASC),
  INDEX `fk_patron_de_evaluacion_variable_de_puesto_laboral1_idx` (`variable_de_puesto_laboral_puesto_laboral_id` ASC, `variable_de_puesto_laboral_variable_id` ASC),
  CONSTRAINT `fk_puesto_laboral_has_variable1_puesto_laboral1`
    FOREIGN KEY (`puesto_laboral_id`)
    REFERENCES `jobplix`.`puesto_laboral` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_puesto_laboral_has_variable1_variable1`
    FOREIGN KEY (`variable_id`)
    REFERENCES `jobplix`.`variable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_puesto_laboral_has_variable1_opciones1`
    FOREIGN KEY (`opcion_id`)
    REFERENCES `jobplix`.`opciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patron_de_evaluacion_variable_de_puesto_laboral1`
    FOREIGN KEY (`variable_de_puesto_laboral_puesto_laboral_id` , `variable_de_puesto_laboral_variable_id`)
    REFERENCES `jobplix`.`variable_de_puesto_laboral` (`puesto_laboral_id` , `variable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`candidato_has_ubigeo_viaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`candidato_has_ubigeo_viaje` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`candidato_has_ubigeo_viaje` (
  `candidato_id` INT NOT NULL,
  `ubigeo_id` INT NOT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`candidato_id`, `ubigeo_id`),
  INDEX `fk_candidato_has_ubigeo_ubigeo1_idx` (`ubigeo_id` ASC),
  INDEX `fk_candidato_has_ubigeo_candidato1_idx` (`candidato_id` ASC),
  CONSTRAINT `fk_candidato_has_ubigeo_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `jobplix`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_has_ubigeo_ubigeo1`
    FOREIGN KEY (`ubigeo_id`)
    REFERENCES `jobplix`.`ubigeo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`candidato_has_variable_de_puesto_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`candidato_has_variable_de_puesto_laboral` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`candidato_has_variable_de_puesto_laboral` (
  `candidato_id` INT NOT NULL,
  `variable_de_puesto_laboral_puesto_laboral_id` INT NOT NULL,
  `variable_de_puesto_laboral_variable_id` INT NOT NULL,
  `fecha_evaluacion` VARCHAR(45) NULL,
  `puntaje` VARCHAR(45) NULL,
  PRIMARY KEY (`candidato_id`, `variable_de_puesto_laboral_puesto_laboral_id`, `variable_de_puesto_laboral_variable_id`),
  INDEX `fk_candidato_has_variable_de_puesto_laboral_variable_de_pue_idx` (`variable_de_puesto_laboral_puesto_laboral_id` ASC, `variable_de_puesto_laboral_variable_id` ASC),
  INDEX `fk_candidato_has_variable_de_puesto_laboral_candidato1_idx` (`candidato_id` ASC),
  CONSTRAINT `fk_candidato_has_variable_de_puesto_laboral_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `jobplix`.`candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_has_variable_de_puesto_laboral_variable_de_puest1`
    FOREIGN KEY (`variable_de_puesto_laboral_puesto_laboral_id` , `variable_de_puesto_laboral_variable_id`)
    REFERENCES `jobplix`.`variable_de_puesto_laboral` (`puesto_laboral_id` , `variable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`Recomendaciones_variable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`Recomendaciones_variable` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`Recomendaciones_variable` (
  `candidato_has_variable_de_puesto_laboral_candidato_id` INT NOT NULL,
  `candidato_has_variable_de_puesto_laboral_variable_de_puesto_laboral_puesto_laboral_id` INT NOT NULL,
  `candidato_has_variable_de_puesto_laboral_variable_de_puesto_laboral_variable_id` INT NOT NULL,
  `por_recomendar` TINYINT(1) NULL,
  INDEX `fk_Recomendaciones_variable_candidato_has_variable_de_puest_idx` (`candidato_has_variable_de_puesto_laboral_candidato_id` ASC, `candidato_has_variable_de_puesto_laboral_variable_de_puesto_laboral_puesto_laboral_id` ASC, `candidato_has_variable_de_puesto_laboral_variable_de_puesto_laboral_variable_id` ASC),
  CONSTRAINT `fk_Recomendaciones_variable_candidato_has_variable_de_puesto_1`
    FOREIGN KEY (`candidato_has_variable_de_puesto_laboral_candidato_id` , `candidato_has_variable_de_puesto_laboral_variable_de_puesto_laboral_puesto_laboral_id` , `candidato_has_variable_de_puesto_laboral_variable_de_puesto_laboral_variable_id`)
    REFERENCES `jobplix`.`candidato_has_variable_de_puesto_laboral` (`candidato_id` , `variable_de_puesto_laboral_puesto_laboral_id` , `variable_de_puesto_laboral_variable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`actividad` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `puntaje` VARCHAR(45) NULL,
  `isdenounced` TINYINT(1) NOT NULL DEFAULT 0,
  `isvalidated` TINYINT(1) NULL DEFAULT 0,
  `experiencia_candidato_id` INT NOT NULL,
  `experiencia_empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actividad_experiencia1_idx` (`experiencia_candidato_id` ASC, `experiencia_empresa_id` ASC),
  CONSTRAINT `fk_actividad_experiencia1`
    FOREIGN KEY (`experiencia_candidato_id` , `experiencia_empresa_id`)
    REFERENCES `jobplix`.`experiencia` (`candidato_id` , `empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`comentario` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`comentario` (
  `testigo_experiencia_candidato_id` INT NOT NULL,
  `testigo_experiencia_empresa_id` INT NOT NULL,
  `testigo_usuario_id` INT NOT NULL,
  `actividad_id` INT NOT NULL,
  PRIMARY KEY (`testigo_experiencia_candidato_id`, `testigo_experiencia_empresa_id`, `testigo_usuario_id`, `actividad_id`),
  INDEX `fk_testigo_has_actividad_actividad1_idx` (`actividad_id` ASC),
  INDEX `fk_testigo_has_actividad_testigo1_idx` (`testigo_experiencia_candidato_id` ASC, `testigo_experiencia_empresa_id` ASC, `testigo_usuario_id` ASC),
  CONSTRAINT `fk_testigo_has_actividad_testigo1`
    FOREIGN KEY (`testigo_experiencia_candidato_id` , `testigo_experiencia_empresa_id` , `testigo_usuario_id`)
    REFERENCES `jobplix`.`testigo` (`experiencia_candidato_id` , `experiencia_empresa_id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_testigo_has_actividad_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `jobplix`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`Datos_recomendacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`Datos_recomendacion` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`Datos_recomendacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Curso` VARCHAR(45) NULL,
  `tags_variables` VARCHAR(45) NULL,
  `tags_rubros` VARCHAR(45) NULL,
  `tags_puestoslaborales` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`usuario` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`testigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`testigo` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`testigo` (
  `usuario_id` INT NOT NULL,
  `candidato_has_educacion_superior_candidato_id` INT NOT NULL,
  `candidato_has_educacion_superior_educacion_superior_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `candidato_has_educacion_superior_candidato_id`, `candidato_has_educacion_superior_educacion_superior_id`),
  INDEX `fk_usuario_has_candidato_has_educacion_superior_candidato_h_idx` (`candidato_has_educacion_superior_candidato_id` ASC, `candidato_has_educacion_superior_educacion_superior_id` ASC),
  INDEX `fk_usuario_has_candidato_has_educacion_superior_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_candidato_has_educacion_superior_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `jobplix`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_candidato_has_educacion_superior_candidato_has1`
    FOREIGN KEY (`candidato_has_educacion_superior_candidato_id` , `candidato_has_educacion_superior_educacion_superior_id`)
    REFERENCES `jobplix`.`candidato_has_educacion_superior` (`candidato_id` , `educacion_superior_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`comentario` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`comentario` (
  `testigo_experiencia_candidato_id` INT NOT NULL,
  `testigo_experiencia_empresa_id` INT NOT NULL,
  `testigo_usuario_id` INT NOT NULL,
  `actividad_id` INT NOT NULL,
  PRIMARY KEY (`testigo_experiencia_candidato_id`, `testigo_experiencia_empresa_id`, `testigo_usuario_id`, `actividad_id`),
  INDEX `fk_testigo_has_actividad_actividad1_idx` (`actividad_id` ASC),
  INDEX `fk_testigo_has_actividad_testigo1_idx` (`testigo_experiencia_candidato_id` ASC, `testigo_experiencia_empresa_id` ASC, `testigo_usuario_id` ASC),
  CONSTRAINT `fk_testigo_has_actividad_testigo1`
    FOREIGN KEY (`testigo_experiencia_candidato_id` , `testigo_experiencia_empresa_id` , `testigo_usuario_id`)
    REFERENCES `jobplix`.`testigo` (`experiencia_candidato_id` , `experiencia_empresa_id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_testigo_has_actividad_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `jobplix`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`calificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`calificacion` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`calificacion` (
  `testigo_experiencia_candidato_id` INT NOT NULL,
  `testigo_experiencia_empresa_id` INT NOT NULL,
  `testigo_usuario_id` INT NOT NULL,
  `actividad_id` INT NOT NULL,
  PRIMARY KEY (`testigo_experiencia_candidato_id`, `testigo_experiencia_empresa_id`, `testigo_usuario_id`, `actividad_id`),
  INDEX `fk_testigo_has_actividad_actividad2_idx` (`actividad_id` ASC),
  INDEX `fk_testigo_has_actividad_testigo2_idx` (`testigo_experiencia_candidato_id` ASC, `testigo_experiencia_empresa_id` ASC, `testigo_usuario_id` ASC),
  CONSTRAINT `fk_testigo_has_actividad_testigo2`
    FOREIGN KEY (`testigo_experiencia_candidato_id` , `testigo_experiencia_empresa_id` , `testigo_usuario_id`)
    REFERENCES `jobplix`.`testigo` (`experiencia_candidato_id` , `experiencia_empresa_id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_testigo_has_actividad_actividad2`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `jobplix`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`servicio_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`servicio_media` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`servicio_media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(45) NULL,
  `html_embebido` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`media` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url-data` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `detalle_actividad_id` INT NOT NULL,
  `detalle_actividad_actividad_id` INT NOT NULL,
  `servicio_media_id` INT NOT NULL,
  `actividad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `actividad_id`),
  INDEX `fk_media_servicio_media1_idx` (`servicio_media_id` ASC),
  INDEX `fk_media_actividad1_idx` (`actividad_id` ASC),
  CONSTRAINT `fk_media_servicio_media1`
    FOREIGN KEY (`servicio_media_id`)
    REFERENCES `jobplix`.`servicio_media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `jobplix`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`testigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`testigo` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`testigo` (
  `usuario_id` INT NOT NULL,
  `candidato_has_educacion_superior_candidato_id` INT NOT NULL,
  `candidato_has_educacion_superior_educacion_superior_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `candidato_has_educacion_superior_candidato_id`, `candidato_has_educacion_superior_educacion_superior_id`),
  INDEX `fk_usuario_has_candidato_has_educacion_superior_candidato_h_idx` (`candidato_has_educacion_superior_candidato_id` ASC, `candidato_has_educacion_superior_educacion_superior_id` ASC),
  INDEX `fk_usuario_has_candidato_has_educacion_superior_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_candidato_has_educacion_superior_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `jobplix`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_candidato_has_educacion_superior_candidato_has1`
    FOREIGN KEY (`candidato_has_educacion_superior_candidato_id` , `candidato_has_educacion_superior_educacion_superior_id`)
    REFERENCES `jobplix`.`candidato_has_educacion_superior` (`candidato_id` , `educacion_superior_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`actividad_ed_superior`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`actividad_ed_superior` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`actividad_ed_superior` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `media_id` INT NOT NULL,
  `media_actividad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actividad_ed_superior_media1_idx` (`media_id` ASC, `media_actividad_id` ASC),
  CONSTRAINT `fk_actividad_ed_superior_media1`
    FOREIGN KEY (`media_id` , `media_actividad_id`)
    REFERENCES `jobplix`.`media` (`id` , `actividad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`comentario_ed_superior`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`comentario_ed_superior` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`comentario_ed_superior` (
  `actividad_ed_superior_id` INT NOT NULL,
  `testigo_usuario_id` INT NOT NULL,
  `testigo_candidato_has_educacion_superior_candidato_id` INT NOT NULL,
  `testigo_candidato_has_educacion_superior_educacion_superior_id` INT NOT NULL,
  `contenido` VARCHAR(255) NULL,
  PRIMARY KEY (`actividad_ed_superior_id`, `testigo_usuario_id`, `testigo_candidato_has_educacion_superior_candidato_id`, `testigo_candidato_has_educacion_superior_educacion_superior_id`),
  INDEX `fk_actividad_ed_superior_has_testigo_testigo1_idx` (`testigo_usuario_id` ASC, `testigo_candidato_has_educacion_superior_candidato_id` ASC, `testigo_candidato_has_educacion_superior_educacion_superior_id` ASC),
  INDEX `fk_actividad_ed_superior_has_testigo_actividad_ed_superior1_idx` (`actividad_ed_superior_id` ASC),
  CONSTRAINT `fk_actividad_ed_superior_has_testigo_actividad_ed_superior1`
    FOREIGN KEY (`actividad_ed_superior_id`)
    REFERENCES `jobplix`.`actividad_ed_superior` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_ed_superior_has_testigo_testigo1`
    FOREIGN KEY (`testigo_usuario_id` , `testigo_candidato_has_educacion_superior_candidato_id` , `testigo_candidato_has_educacion_superior_educacion_superior_id`)
    REFERENCES `jobplix`.`testigo` (`usuario_id` , `candidato_has_educacion_superior_candidato_id` , `candidato_has_educacion_superior_educacion_superior_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobplix`.`calificacion_ed_superior`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobplix`.`calificacion_ed_superior` ;

CREATE TABLE IF NOT EXISTS `jobplix`.`calificacion_ed_superior` (
  `actividad_ed_superior_id` INT NOT NULL,
  `testigo_usuario_id` INT NOT NULL,
  `testigo_candidato_has_educacion_superior_candidato_id` INT NOT NULL,
  `testigo_candidato_has_educacion_superior_educacion_superior_id` INT NOT NULL,
  `contenido` VARCHAR(255) NULL,
  PRIMARY KEY (`actividad_ed_superior_id`, `testigo_usuario_id`, `testigo_candidato_has_educacion_superior_candidato_id`, `testigo_candidato_has_educacion_superior_educacion_superior_id`),
  INDEX `fk_actividad_ed_superior_has_testigo1_testigo1_idx` (`testigo_usuario_id` ASC, `testigo_candidato_has_educacion_superior_candidato_id` ASC, `testigo_candidato_has_educacion_superior_educacion_superior_id` ASC),
  INDEX `fk_actividad_ed_superior_has_testigo1_actividad_ed_superior_idx` (`actividad_ed_superior_id` ASC),
  CONSTRAINT `fk_actividad_ed_superior_has_testigo1_actividad_ed_superior1`
    FOREIGN KEY (`actividad_ed_superior_id`)
    REFERENCES `jobplix`.`actividad_ed_superior` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_ed_superior_has_testigo1_testigo1`
    FOREIGN KEY (`testigo_usuario_id` , `testigo_candidato_has_educacion_superior_candidato_id` , `testigo_candidato_has_educacion_superior_educacion_superior_id`)
    REFERENCES `jobplix`.`testigo` (`usuario_id` , `candidato_has_educacion_superior_candidato_id` , `candidato_has_educacion_superior_educacion_superior_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
